//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marmara.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblExam()
        {
            this.tblQuestions = new HashSet<tblQuestion>();
            this.tblUserExams = new HashSet<tblUserExam>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> LessonId { get; set; }
        public Nullable<bool> Status { get; set; }
        public string StartPage { get; set; }
        public string EndPage { get; set; }
        public Nullable<int> ExamTimeLimit { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<bool> FourFalseOneTrue { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<bool> FiveAnswerOrNot { get; set; }
        public string PdfName { get; set; }
        public Nullable<int> SertificateScore { get; set; }
    
        public virtual tblLesson tblLesson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblQuestion> tblQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserExam> tblUserExams { get; set; }
    }
}
