//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marmara.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestion
    {
        public int Id { get; set; }
        public Nullable<int> ExamId { get; set; }
        public string TrueAnswer { get; set; }
        public Nullable<int> Row { get; set; }
        public string Description { get; set; }
    
        public virtual tblExam tblExam { get; set; }
    }
}
