//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marmara.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserExam
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ExamId { get; set; }
        public Nullable<int> ProofImageId { get; set; }
        public Nullable<bool> IsExamStarted { get; set; }
        public Nullable<System.DateTime> AttemptDate { get; set; }
        public Nullable<bool> IsExamEnd { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<bool> IsSertificateHas { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> Attempts { get; set; }
        public Nullable<decimal> EndScore { get; set; }
        public Nullable<int> TrueAnswerCount { get; set; }
        public Nullable<int> FalseAnswerCount { get; set; }
        public Nullable<int> EmptyAnswerCount { get; set; }
    
        public virtual tblExam tblExam { get; set; }
        public virtual tblImage tblImage { get; set; }
        public virtual User User { get; set; }
    }
}
