//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marmara.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.tblUserExams = new HashSet<tblUserExam>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string BirthDate { get; set; }
        public Nullable<bool> IsMale { get; set; }
        public Nullable<int> ImageId { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public string Token { get; set; }
        public Nullable<bool> Status { get; set; }
        public string OnlineLessonPermission { get; set; }
        public string Role { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsOnlineStudent { get; set; }
    
        public virtual tblImage tblImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserExam> tblUserExams { get; set; }
    }
}
